services:
  server:
    image: bonsai-life-support/server
    build:
      context: server
      target: serve
    ports:
      - 35000:35000
    user: root
    environment:
      - ENV SERVER_HOST=0.0.0.0
      - ENV SERVER_PORT=35000
      - DB_HOST=mongodb://mongodb:27017/bonsai-life-support-production
      - SERVER_LOGGING=true
    volumes:
      - ./server:/usr/src/app

  gui-browser:
    image: bonsai-life-support/gui-browser
    build:
      context: gui-browser
    ports:
      - 3000:3000
    volumes:
      - ./gui-browser:/usr/src/app

  mongodb:
    image: mongo
    ports:
      - 27017:27017
